# Generated by Django 4.2.1 on 2025-05-15 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shurpa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shurpa',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shurpa',
            name='calorie',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calorie', to='shurpa.calorie', verbose_name='Калории'),
        ),
        migrations.AddField(
            model_name='shurpa',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='shurpa.category', verbose_name='Каталог'),
        ),
        migrations.AddField(
            model_name='shurpa',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='shurpa.tagpost', verbose_name='Тэги'),
        ),
    ]
